### PR TITLE
Replace StackWalker with OriginalSourceInterpreter

### PR DESCRIPTION
**Pull request by EpicPlayerA10**
I found out that there exists a much better solution to obtain original source value of the stack value. Just use the built-in `Interpreter` class in ASM lib. They offer much more complete, stable and better implementation of tracking stack values, and every copy-like instruction is already implemented! No need to write something like `StackWalker` from scratch which was missing some instructions to handle.

For more details see javadoc of field `OriginalSourceValue#originalSource` (it is nearly the same javadoc of the removed method `StackWalker#getOnlyOnePossibleProducer`)

## Changes
- Deleted `StackWalker`
- Created `OriginalSourceValue` and `OriginalSourceInterpreter` which is a slightly modified version of original `SourceInterpreter`. This is meant to track stack copies (see `OriginalSourceInterpreter#copyOperation`)

### CODE REVIEW

**Comment by narumii** [comment]
I would leave the stackwalker, it may come handy later

**Comment by EpicPlayerA10** [comment]
> I would leave the stackwalker, it may come handy later

I mean that `OriginalSourceInterpreter` is better version of `StackWalker` because it solves more problems and it already implement all copy-like instructions. Also I discovered that `StackWalker` had some issues with throwing `StackOverflowError` in some scenarios.

**Comment by Janmm14** [comment]
Why copy dependency classes into the project, just depend on asm analysis or whatever package it is

**Comment by EpicPlayerA10** [comment]
> Why copy dependency classes into the project, just depend on asm analysis or whatever package it is

I couldn't because I needed to change generic from `SourceValue` to my own `OriginalSourceValue`. I couldn't just extend that class.

**Pull request merged**
