### PR TITLE
Fix binscure clinit remover

### PR DESCRIPTION
**Pull request by NaulbiMIX**

### CODE REVIEW

**Comment by narumii** [comment]
Okey so what this fix is fixing? (If i can know)

**Comment by NaulbiMIX** [comment]
Through the debug, you can see that not all clinit is deleted, removal is required in the original classic, because of this, binsecure is not fully deobfected. 

I made a mistake in the old and latest transformers, this is the latest transformer, not the old one. 

This fix is more than about two months old, I tested it personally on the deobfuscation of this - https://github.com/MineMarket/mMarketManage/releases/download/1.2/mMarketManage-release.jar

**Comment by narumii** [comment]
Original classes are used only for sandbox and when deobfuscated class can't be saved(as replecement) so it shouldn't be modified.

**Comment by NaulbiMIX** [comment]
If you do not use the sandbox classes are not saved, respectively, using it and fixes on clinit everything works as it should. Once again, these are fixes for the old version of the deobf, if all this is fixed in the new one, then they are not required.

**Comment by narumii** [comment]
Original classes are used for sandbox and when deobfuscated class can't be saved deobfuscator will use original class instead without modified code. In your commit only 1 thing has changed and this is removing method from original classes and original class should be untouched.

https://github.com/narumii/Deobfuscator/blob/5d03fd1f492d251a1d2cdfcedfb6ba3bb515f30a/src/main/java/uwu/narumi/deobfuscator/Deobfuscator.java#L148
https://github.com/narumii/Deobfuscator/blob/5d03fd1f492d251a1d2cdfcedfb6ba3bb515f30a/src/main/java/uwu/narumi/deobfuscator/transformer/impl/paramorphism/ParamorphismInvokeDynamicTransformer.java#L27

**Comment by NaulbiMIX** [comment]
close

**Pull request closed without merging**
