### PR TITLE
Fix jar -> directory output and add test from #89

### PR DESCRIPTION
**Pull request by sencrash**

### CODE REVIEW

**Review by EpicPlayerA10 — CHANGES_REQUESTED** [review]
You thrown a `SnakeGame` jar but not obfuscated. 

The rest looks good to me.

**Comment by sencrash** [comment]
> You thrown a `SnakeGame` jar but not obfuscated.
> 
> The rest looks good to me.

Ah, forgot to put it back

**Review by EpicPlayerA10 — CHANGES_REQUESTED** [review]
One more thing: Rename jar to original name `SnakeGame-obf-zkm.jar` for readability that this jar was obfuscated using zkm.

**Review by EpicPlayerA10 — APPROVED** [review]
Thank you very much :D

**Pull request merged**
