### PR TITLE
Add sample ZKM Obf jar

### PR DESCRIPTION
**Pull request by THCFree**
Added sample ZKM 21 sample jar original jar is available on the following URL: https://jnic.dev/samples/SnakeGame.jar

### CODE REVIEW

**Review by EpicPlayerA10 — CHANGES_REQUESTED** [review]
You forgot to connect the sample jar in https://github.com/narumii/Deobfuscator/blob/master/deobfuscator-impl/src/test/java/uwu/narumi/deobfuscator/TestDeobfuscation.java

**Comment by sencrash** [comment]
> You forgot to connect the sample jar in https://github.com/narumii/Deobfuscator/blob/master/deobfuscator-impl/src/test/java/uwu/narumi/deobfuscator/TestDeobfuscation.java

Going to create my own PR for this, since there are some issues with jar files + folder saving and the resulting decompilation tests

**Comment by EpicPlayerA10** [comment]
Hmm interesting, but it may be possible that it is broken

**Comment by EpicPlayerA10** [comment]
I'm very sorry, but superseded by #91. If you need credits then let me know or create a PR.

**Pull request closed without merging**
